package br.com.gsst.model;
// Generated 22/07/2016 22:11:44 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.constraints.NotBlank;

/**
 * Maquina generated by hbm2java
 */
@Entity
@Table(name = "maquina", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "num_patrimonio")
)
public class Maquina implements java.io.Serializable {

    private int idMaquina;
    private Unidade unidade;
    @NotBlank(message = "{maquina.numPatrimonio.blank}")
    private String numPatrimonio;
    private String descricao;
    private Set<Processo> processos = new HashSet(0);

    public Maquina() {
    }

    public Maquina(int idMaquina, Unidade unidade) {
        this.idMaquina = idMaquina;
        this.unidade = unidade;
    }

    public Maquina(int idMaquina, Unidade unidade, String numPatrimonio, String descricao, Set processos) {
        this.idMaquina = idMaquina;
        this.unidade = unidade;
        this.numPatrimonio = numPatrimonio;
        this.descricao = descricao;
        this.processos = processos;
    }

    @Id

    @Column(name = "id_maquina", unique = true, nullable = false)
    public int getIdMaquina() {
        return this.idMaquina;
    }

    public void setIdMaquina(int idMaquina) {
        this.idMaquina = idMaquina;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_unidade", nullable = false)
    public Unidade getUnidade() {
        return this.unidade;
    }

    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

    @Column(name = "num_patrimonio", unique = true)
    public String getNumPatrimonio() {
        return this.numPatrimonio;
    }

    public void setNumPatrimonio(String numPatrimonio) {
        this.numPatrimonio = numPatrimonio;
    }

    @Column(name = "descricao")
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "maquina")
    public Set<Processo> getProcessos() {
        return this.processos;
    }

    public void setProcessos(Set processos) {
        this.processos = processos;
    }

}
