package br.com.gsst.model;
// Generated 22/07/2016 22:11:44 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Nr generated by hbm2java
 */
@Entity
@Table(name = "nr", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "numero")
)
public class Nr implements java.io.Serializable {

    private int idNr;
    private Nr nr;
    private String numero;
    private String titulo;
    private String descricao;
    private char tipo;
    private int nivel;
    private Date dataInsercao;
    private Set<Processo> processos = new HashSet(0);
    private Set<Nr> nrs = new HashSet(0);

    public Nr() {
    }

    public Nr(int idNr, String numero, String titulo, char tipo, int nivel) {
        this.idNr = idNr;
        this.numero = numero;
        this.titulo = titulo;
        this.tipo = tipo;
        this.nivel = nivel;
    }

    public Nr(int idNr, Nr nr, String numero, String titulo, String descricao, char tipo, int nivel, Date dataInsercao, Set processos, Set nrs) {
        this.idNr = idNr;
        this.nr = nr;
        this.numero = numero;
        this.titulo = titulo;
        this.descricao = descricao;
        this.tipo = tipo;
        this.nivel = nivel;
        this.dataInsercao = dataInsercao;
        this.processos = processos;
        this.nrs = nrs;
    }

    @Id

    @Column(name = "id_nr", unique = true, nullable = false)
    public int getIdNr() {
        return this.idNr;
    }

    public void setIdNr(int idNr) {
        this.idNr = idNr;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_nr_item")
    public Nr getNr() {
        return this.nr;
    }

    public void setNr(Nr nr) {
        this.nr = nr;
    }

    @Column(name = "numero", unique = true, nullable = false)
    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    @Column(name = "titulo", nullable = false)
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Column(name = "descricao")
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Column(name = "tipo", nullable = false, length = 1)
    public char getTipo() {
        return this.tipo;
    }

    public void setTipo(char tipo) {
        this.tipo = tipo;
    }

    @Column(name = "nivel", nullable = false)
    public int getNivel() {
        return this.nivel;
    }

    public void setNivel(int nivel) {
        this.nivel = nivel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "data_insercao", length = 29)
    public Date getDataInsercao() {
        return this.dataInsercao;
    }

    public void setDataInsercao(Date dataInsercao) {
        this.dataInsercao = dataInsercao;
    }

    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "nrs")
    public Set<Processo> getProcessos() {
        return this.processos;
    }

    public void setProcessos(Set processos) {
        this.processos = processos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "nr")
    public Set<Nr> getNrs() {
        return this.nrs;
    }

    public void setNrs(Set nrs) {
        this.nrs = nrs;
    }

}
