package br.com.gsst.model;
// Generated 22/07/2016 22:11:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Valores generated by hbm2java
 */
@Entity
@Table(name = "valores", schema = "public"
)
public class Valores implements java.io.Serializable {

    private int idValores;
    private char tipo;
    private int nivel;
    private BigDecimal valor;

    public Valores() {
    }

    public Valores(int idValores, char tipo, int nivel, BigDecimal valor) {
        this.idValores = idValores;
        this.tipo = tipo;
        this.nivel = nivel;
        this.valor = valor;
    }

    @Id

    @Column(name = "id_valores", unique = true, nullable = false)
    public int getIdValores() {
        return this.idValores;
    }

    public void setIdValores(int idValores) {
        this.idValores = idValores;
    }

    @Column(name = "tipo", nullable = false, length = 1)
    public char getTipo() {
        return this.tipo;
    }

    public void setTipo(char tipo) {
        this.tipo = tipo;
    }

    @Column(name = "nivel", nullable = false)
    public int getNivel() {
        return this.nivel;
    }

    public void setNivel(int nivel) {
        this.nivel = nivel;
    }

    @Column(name = "valor", nullable = false, precision = 8)
    public BigDecimal getValor() {
        return this.valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

}
