/*
	Inserção das NRs
	Autor: José Carlos de Freitas
	Data: 23/07/2016, 22:00
*/


BEGIN;

INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('01', 'Disposições Gerais', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('02', 'Inspeção Prévia', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('03', 'Embargo ou Interdição', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('04', 'Serviços Especializados em Engenharia de Segurança e em Medicina do Trabalho', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('05', 'Comissão Interna de Prevenção de Acidentes', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('06', 'Equipamentos de Proteção Individual (EPI)', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('07', 'Programas de Controle Médico de Saúde Ocupacional (PCMSO)', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('08', 'Edificações', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('09', 'Programas de Prevenção de Riscos Ambientais', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('10', 'Segurança em Instalações e Serviços em Eletricidade', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('11', 'Transporte, Movimentação, Armazenagem e Manuseio de Materiais', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('12', 'Segurança no Trabalho em Máquinas e Equipamentos', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('13', 'Caldeiras, Vasos de Pressão e Tubulações.', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('14', 'Fornos', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('15', 'Atividades e Operações Insalubres', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('16', 'Atividades e Operações Perigosas', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('17', 'Ergonomia', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('18', 'Condições e Meio Ambiente de Trabalho na Indústria da Construção', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('19', 'Explosivos', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('20', 'Segurança e Saúde no Trabalho com Inflamáveis e Combustíveis', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('21', 'Trabalho a Céu Aberto', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('22', 'Segurança e Saúde Ocupacional na Mineração', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('23', 'Proteção Contra Incêndios', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('24', 'Condições Sanitárias e de Conforto nos Locais de Trabalho', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('25', 'Resíduos Industriais', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('26', 'Sinalização de Segurança', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('27', 'Registro Profissional do Técnico de Segurança do Trabalho no MTB', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('28', 'Fiscalização e Penalidades', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('29', 'Segurança e Saúde no Trabalho Portuário', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('30', 'Segurança e Saúde no Trabalho Aquaviário', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('31', 'Segurança e Saúde no Trabalho na Agricultura, Pecuária Silvicultura, Exploração Florestal e Aqüicultura', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('32', 'Segurança e Saúde no Trabalho em Estabelecimentos de Saúde', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('33', 'Segurança e Saúde no Trabalho em Espaços Confinados', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('34', 'Condições e Meio Ambiente de Trabalho na Indústria da Construção e Reparação Naval', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('35', 'Trabalho em Altura', now());
INSERT INTO public.nr(numero, descricao, data_insercao) VALUES ('36', 'Segurança e Saúde no Trabalho em Empresas de Abate e Processamento de Carnes e Derivados', now());






--NR1
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.1', 'As Normas Regulamentadoras - NR, relativas à segurança e medicina do trabalho, são de observância obrigatória pelas empresas privadas e públicas e pelos órgãos públicos da administração direta e indireta, bem como pelos órgãos dos Poderes Legislativo e Judiciário, que possuam empregados regidos pela Consolidação das Leis do Trabalho - CLT. (Alteração dada pela Portaria n.º 06, de 09/03/83)', (SELECT id_nr FROM nr WHERE numero ilike '01'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.1.1', 'As disposições contidas nas Normas Regulamentadoras – NR aplicam-se, no que couber, aos trabalhadores avulsos, às entidades ou empresas que lhes tomem o serviço e aos sindicatos representativos das respectivas categorias profissionais. (Alteração dada pela Portaria n.º 06, de 09/03/83)', (SELECT id_nr FROM nr WHERE numero ilike '1.1'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.2', 'A observância das Normas Regulamentadoras - NR não desobriga as empresas do cumprimento de outras disposições que, com relação à matéria, sejam incluídas em códigos de obras ou regulamentos sanitários dos Estados ou Municípios, e outras, oriundas de convenções e acordos coletivos de trabalho. (Alteração dada pela Portaria n.º 06, de 09/03/83)', (SELECT id_nr FROM nr WHERE numero ilike '01'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.3', 'A Secretaria de Segurança e Saúde no Trabalho - SSST é o órgão de âmbito nacional competente para coordenar, orientar, controlar e supervisionar as atividades relacionadas com a segurança e medicina do trabalho, inclusive a Campanha Nacional de Prevenção de Acidentes do Trabalho - CANPAT, o Programa de Alimentação do Trabalhador - PAT e ainda a fiscalização do cumprimento dos preceitos legais e regulamentares sobre segurança e medicina do trabalho em todo o território nacional. (Alteração dada pela Portaria n.º 13, de 17/09/93)', (SELECT id_nr FROM nr WHERE numero ilike '01'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.3.1', 'Compete, ainda, à Secretaria de Segurança e Saúde no Trabalho - SSST conhecer, em última instância, dos recursos voluntários ou de ofício, das decisões proferidas pelos Delegados Regionais do Trabalho, em matéria de segurança e saúde no trabalho. (Alteração dada pela Portaria n.º 13, de 17/09/93)', (SELECT id_nr FROM nr WHERE numero ilike '1.3'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.4', 'A Delegacia Regional do Trabalho - DRT, nos limites de sua jurisdição, é o órgão regional competente para executar as atividades relacionadas com a segurança e medicina do trabalho, inclusive a Campanha Nacional de Prevenção dos Acidentes do Trabalho - CANPAT, o Programa de Alimentação do Trabalhador - PAT e ainda a fiscalização do cumprimento dos preceitos legais e regulamentares sobre segurança e medicina do trabalho. (Alteração dada pela Portaria n.º 13, de 17/09/93)', (SELECT id_nr FROM nr WHERE numero ilike '01'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.4.1', 'Compete, ainda, à Delegacia Regional do Trabalho - DRT ou à Delegacia do Trabalho Marítimo - DTM, nos limites de sua jurisdição: (Alteração dada pela Portaria n.º 06, de 09/03/83) a) adotar medidas necessárias à fiel observância dos preceitos legais e regulamentares sobre segurança e medicina do trabalho; b) impor as penalidades cabíveis por descumprimento dos preceitos legais e regulamentares sobre segurança e medicina do trabalho; c) embargar obra, interditar estabelecimento, setor de serviço, canteiro de obra, frente de trabalho, locais de trabalho, máquinas e equipamentos; d) notificar as empresas, estipulando prazos, para eliminação e/ou neutralização de insalubridade; e) atender requisições judiciais para realização de perícias sobre segurança e medicina do trabalho nas localidades onde não houver Médico do Trabalho ou Engenheiro de Segurança do Trabalho registrado no MTb.', (SELECT id_nr FROM nr WHERE numero ilike '1.4'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.5', 'Podem ser delegadas a outros órgãos federais, estaduais e municipais, mediante convênio autorizado pelo Ministro do Trabalho, atribuições de fiscalização e/ou orientação às empresas, quanto ao cumprimento dos preceitos legais e regulamentares sobre segurança e medicina do trabalho. (Alteração dada pela Portaria n.º 06, de 09/03/83)', (SELECT id_nr FROM nr WHERE numero ilike '01'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.6', 'Para fins de aplicação das Normas Regulamentadoras – NR, considera-se: (Alteração dada pela Portaria n.º 06, de 09/03/83) a) empregador, a empresa individual ou coletiva, que, assumindo os riscos da atividade econômica, admite, assalaria e dirige a prestação pessoal de serviços. Equiparam-se ao empregador os profissionais liberais, as  2 instituições de beneficência, as associações recreativas ou outras instituições sem fins lucrativos, que admitem trabalhadores como empregados; b) empregado, a pessoa física que presta serviços de natureza não eventual a empregador, sob a dependência deste e mediante salário; c) empresa, o estabelecimento ou o conjunto de estabelecimentos, canteiros de obra, frente de trabalho, locais de trabalho e outras, constituindo a organização de que se utiliza o empregador para atingir seus objetivos; d) estabelecimento, cada uma das unidades da empresa, funcionando em lugares diferentes, tais como: fábrica, refinaria, usina, escritório, loja, oficina, depósito, laboratório; e) setor de serviço, a menor unidade administrativa ou operacional compreendida no mesmo estabelecimento; f) canteiro de obra, a área do trabalho fixa e temporária, onde se desenvolvem operações de apoio e execução à construção, demolição ou reparo de uma obra; g) frente de trabalho, a área de trabalho móvel e temporária, onde se desenvolvem operações de apoio e execução à construção, demolição ou reparo de uma obra; h) local de trabalho, a área onde são executados os trabalhos.', (SELECT id_nr FROM nr WHERE numero ilike '01'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.6.1', 'Sempre que uma ou mais empresas, tendo, embora, cada uma delas, personalidade jurídica própria, estiverem sob direção, controle ou administração de outra, constituindo grupo industrial, comercial ou de qualquer outra atividade econômica, serão, para efeito de aplicação das Normas Regulamentadoras - NR, solidariamente responsáveis a empresa principal e cada uma das subordinadas. (Alteração dada pela Portaria n.º 06, de 09/03/83)', (SELECT id_nr FROM nr WHERE numero ilike '1.6'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.6.2', 'Para efeito de aplicação das Normas Regulamentadoras - NR, a obra de engenharia, compreendendo ou não canteiro de obra ou frentes de trabalho, será considerada como um estabelecimento, a menos que se disponha, de forma diferente, em NR específica. (Alteração dada pela Portaria n.º 06, de 09/03/83)', (SELECT id_nr FROM nr WHERE numero ilike '1.6'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.7', 'Cabe ao empregador: (Alteração dada pela Portaria n.º 06, de 09/03/83) a) cumprir e fazer cumprir as disposições legais e regulamentares sobre segurança e medicina do trabalho; b) elaborar ordens de serviço sobre segurança e saúde no trabalho, dando ciência aos empregados por comunicados, cartazes ou meios eletrônicos; (Alteração dada pela Portaria n.º 84, de 04/03/09) Obs.: Com a alteração dada pela Portaria n.º 84, de 04/03/09, todos os incisos (I, II, III, IV, V e VI) desta alínea foram revogados. c) informar aos trabalhadores: (Alteração dada pela Portaria n.º 03, de 07/02/88) I. os riscos profissionais que possam originar-se nos locais de trabalho; II. os meios para prevenir e limitar tais riscos e as medidas adotadas pela empresa; III. os resultados dos exames médicos e de exames complementares de diagnóstico aos quais os próprios trabalhadores forem submetidos; IV. os resultados das avaliações ambientais realizadas nos locais de trabalho. d) permitir que representantes dos trabalhadores acompanhem a fiscalização dos preceitos legais e regulamentares sobre segurança e medicina do trabalho; (Alteração dada pela Portaria n.º 03, de 07/02/88) e) determinar procedimentos que devem ser adotados em caso de acidente ou doença relacionada ao trabalho. (Inserção dada pela Portaria n.º 84, de 04/03/09)', (SELECT id_nr FROM nr WHERE numero ilike '01'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.8', 'Cabe ao empregado: (Alteração dada pela Portaria n.º 06, de 09/03/83) a) cumprir as disposições legais e regulamentares sobre segurança e saúde do trabalho, inclusive as ordens de serviço expedidas pelo empregador; (Alteração dada pela Portaria n.º 84, de 04/03/09) b) usar o EPI fornecido pelo empregador; c) submeter-se aos exames médicos previstos nas Normas Regulamentadoras - NR; d) colaborar com a empresa na aplicação das Normas Regulamentadoras - NR;', (SELECT id_nr FROM nr WHERE numero ilike '01'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.8.1', 'Constitui ato faltoso a recusa injustificada do empregado ao cumprimento do disposto no item anterior. (Alteração dada pela Portaria n.º 06, de 09/03/83)', (SELECT id_nr FROM nr WHERE numero ilike '1.8'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.9', 'O não-cumprimento das disposições legais e regulamentares sobre segurança e medicina do trabalho acarretará  3 ao empregador a aplicação das penalidades previstas na legislação pertinente. (Alteração dada pela Portaria n.º 06, de 09/03/83)', (SELECT id_nr FROM nr WHERE numero ilike '01'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('1.10', 'As dúvidas suscitadas e os casos omissos verificados na execução das Normas Regulamentadoras – NR, serão decididos pela Secretaria de Segurança e Medicina do Trabalho - SSMT. (Alteração dada pela Portaria n.º 06, de 09/03/83)', (SELECT id_nr FROM nr WHERE numero ilike '01'));



--NR2
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('2.1', 'Todo estabelecimento novo, antes de iniciar suas atividades, deverá solicitar aprovação de suas instalações ao órgão regional do MTb. (Alteração dada pela Portaria n.º 35, de 28/12/83)', (SELECT id_nr FROM nr WHERE numero ilike '02'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('2.2', 'O órgão regional do MTb, após realizar a inspeção prévia, emitirá o Certificado de Aprovação de Instalações - CAI, conforme modelo anexo. (Alteração dada pela Portaria n.º 35, de 28/12/83)', (SELECT id_nr FROM nr WHERE numero ilike '02'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('2.3', 'A empresa poderá encaminhar ao órgão regional do MTb uma declaração das instalações do estabelecimento novo, conforme modelo anexo, que poderá ser aceita pelo referido órgão, para fins de fiscalização, quando não for possível realizar a inspeção prévia antes de o estabelecimento iniciar suas atividades. (Alteração dada pela Portaria n.º 35, de 28/12/83)', (SELECT id_nr FROM nr WHERE numero ilike '02'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('2.4', 'A empresa deverá comunicar e solicitar a aprovação do órgão regional do MTb, quando ocorrer modificações substanciais nas instalações e/ou nos equipamentos de seu(s) estabelecimento(s). (Alteração dada pela Portaria n.º 35, de 28/12/83)', (SELECT id_nr FROM nr WHERE numero ilike '02'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('2.5', 'É facultado às empresas submeter à apreciação prévia do órgão regional do MTb os projetos de construção e respectivas instalações. (Alteração dada pela Portaria n.º 35, de 28/12/83)', (SELECT id_nr FROM nr WHERE numero ilike '02'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('2.6', 'A inspeção prévia e a declaração de instalações, referidas nos itens 2.1 e 2.3, constituem os elementos capazes de assegurar que o novo estabelecimento inicie suas atividades livre de riscos de acidentes e/ou de doenças do trabalho, razão pela qual o estabelecimento que não atender ao disposto naqueles itens fica sujeito ao impedimento de seu funcionamento, conforme estabelece o art. 160 da CLT, até que seja cumprida a exigência deste artigo. (Alteração dada pela Portaria n.º 35, de 28/12/83)', (SELECT id_nr FROM nr WHERE numero ilike '02'));


--nr3
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('3.1', 'Embargo e interdição são medidas de urgência, adotadas a partir da constatação de situação de trabalho que caracterize risco grave e iminente ao trabalhador. ', (SELECT id_nr FROM nr WHERE numero ilike '03'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('3.1.1', 'Considera-se grave e iminente risco toda condição ou situação de trabalho que possa causar acidente ou doença relacionada ao trabalho com lesão grave à integridade física do trabalhador.', (SELECT id_nr FROM nr WHERE numero ilike '3.1'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('3.2', 'A interdição implica a paralisação total ou parcial do estabelecimento, setor de serviço, máquina ou equipamento. ', (SELECT id_nr FROM nr WHERE numero ilike '03'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('3.3', 'O embargo implica a paralisação total ou parcial da obra. ', (SELECT id_nr FROM nr WHERE numero ilike '03'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('3.3.1', 'Considera-se obra todo e qualquer serviço de engenharia de construção, montagem, instalação, manutenção ou reforma.', (SELECT id_nr FROM nr WHERE numero ilike '3.3'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('3.4', 'Durante a vigência da interdição ou do embargo, podem ser desenvolvidas atividades necessárias à correção da situação de grave e iminente risco, desde que adotadas medidas de proteção adequadas dos trabalhadores envolvidos. ', (SELECT id_nr FROM nr WHERE numero ilike '03'));
INSERT INTO public.nr(numero, descricao, id_nr_item) VALUES ('3.5', 'Durante a paralisação decorrente da imposição de interdição ou embargo, os empregados devem receber os salários como se estivessem em efetivo exercício.', (SELECT id_nr FROM nr WHERE numero ilike '03'));

COMMIT;